// Generated by CoffeeScript 1.6.2
(function() {
  var api, app, express, routes;

  express = require('express');

  routes = require('./routes');

  api = require('./routes/api');

  app = module.exports = express();

  app.configure(function() {
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express["static"](__dirname + '/public'));
    return app.use(app.router);
  });

  app.configure('development', function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure('production', function() {
    return app.use(express.errorHandler());
  });

  app.get('/', routes.index);

  app.get('/partial/:name', routes.partial);

  app.get('/api/name', api.name);

  app.get('*', routes.index);

  app.listen(3000, function() {
    return console.log("Server started");
  });

}).call(this);
